# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
# define global settings here
# name: exampleapp # application name
# registry: exampleuser # dockerhub username or container registry hostname

# define multiple services here
containerEngine: docker
# registry: localhost:5000
services:
  - name: chat-server
    project: chat-server/chat-server.csproj
    bindings:
      - protocol: https
        port: 11000
        connectionString: ${protocol}://${host}:${port}
  - name: chat-server-backend
    project: chat-server-backend/chat-server-backend.csproj
    bindings:
      - protocol: https
        port: 12000
        connectionString: ${protocol}://${host}:${port}
  - name: auth-server
    image: quay.io/keycloak/keycloak
    args: start-dev
    env:
      - name: KC_DB
        value: postgres
      - name: KC_DB_URL_HOST
        value: postgres
      - name: KC_DB_URL_DATABASE
        value: postgres
      - name: KC_DB_PASSWORD
        value: pass@word1
      - name: KC_DB_USERNAME
        value: postgres
      - name: KC_DB_SCHEMA
        value: keycloak
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: admin
    bindings:
      - port: 10000
        containerPort: 8080
        protocol: http
        connectionString: ${protocol}://${host}:${port}
  - name: postgres
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: "pass@word1"
    bindings:
      - port: 5432
        connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
    volumes:
      - source: postgres-storage
        target: /var/lib/postgresql/data
  - name: frontend
    executable: cmd
    args: "/c npm run dev"
    workingDirectory: ./frontend/
    bindings:
      - port: 5173
        protocol: http
        connectionString: ${protocol}://${host}:${port}
